### ISSUE TITLE
safe vs. unsafe FFI calls

### ISSUE THREAD

**Issue by iustin** [redneb/disk-free-space#1]
The import of statvfs is:

```
foreign import ccall unsafe statvfs :: CString -> Ptr a -> IO CInt
```

Since this function is doing a system call, I'm not sure why it is marked as unsafe - in case of remote filesystems, this could block for a long time (in real world terms). What do you think about making this `safe`, since the overhead of the syscall will anyway make the Haskell RTS overhead most likely moot?

**Comment by redneb** [comment]
I don't feel strongly about either way. I was merely following the convention followed by other packages that system calls that do not generally block are imported as `unsafe`. Examples of that are `unlink(2)`, `rename(2)`, `chown(2)`, `stat(2)` in the `unix` package. All of those function suffer from the same possible issue that you mention.

**Comment by iustin** [comment]
Interesting, thanks for the info - I'll followup there and then update this issue.

**Comment by iustin** [comment]
FYI, on haskell/unix#34, the agreement is that unsafe is the wrong approach. I'll try to send a pull request later this week (if you don't beat me to it).

**Comment by redneb** [comment]
I just uploaded a new version (v0.1.0.1) on hackage for that. Thanks for the report.
